### ISSUE TITLE
Trying to build for UE5.2.0

### ISSUE THREAD

**Issue by tylru** [zompi2/UE4EasyLocalizationTool#5]
Sadly cannot seem to make use of this plugin in Unreal Engine 5.2.0. Are there any plans to update it to support that version?

![image](https://github.com/zompi2/UE4EasyLocalizationTool/assets/22118920/cb8b3512-4773-416c-a02b-db188c419434)

Many thanks!

**Comment by zompi2** [comment]
Hi!

I will look at this, but I can't promise when. I will try do it this week.

Thanks for pointing it out!

**Comment by zompi2** [comment]
I made some changes and commited them to the branch ue52: https://github.com/zompi2/UE4EasyLocalizationTool/tree/ue52
Can you check and verify if this works on your machine?

**Comment by zompi2** [comment]
Fixes for UE5 support has been merged into the main branch. Closing this issue.
