### ISSUE TITLE
Is there a provided list of language codes? "lang-??"

### ISSUE THREAD

**Issue by tylru** [zompi2/UE4EasyLocalizationTool#6]
Sorry for multiple issues, but to keep better track of them I thought it made sense to make separate ones.

Is there a list of language codes that the plugin supports, or is it influenced in some way by Unreal? If so, are you aware of a list of language codes that can be used in the spreadsheet column headers?

Right now we are using this (based on Google's own standard):

English (United Kingdom)	-	en-gb
English (American)			-	en-us
French					-	fr
Italian					-	it
Dutch					-	nl
German					-	de
Russian					-	ru
Spanish					-	es
Portuguese				-	pt
Polish					-	pl
Turkish					-	tr
Chinese (Simplified)		-	zh-CN
Chinese (Traditional)		-	zh-TW
Korean					-	ko
Japanese					-	ja
Thai						-	th

**Comment by zompi2** [comment]
Hi!

Unreal uses ICU library to handle localization. You can check the `Engine/Content/Internationalization/All/icudt64l` directory to check the code of the localization resource. 

The online list of ICU codes can be found here: https://www.localeplanet.com/icu/

Chinese codes are: `zh-Hans` for simplified and `zh-Hant` for traditional.

Actually I'm not sure if the codes must be exact as in the ICU library or you can use anything you put to the cvs... but here I'm not 100% sure ;)

**Comment by zompi2** [comment]
The link to the list of supported ICU codes has been added to Readme. Closing issue.
